# Generated by Django 2.1 on 2018-08-28 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180828_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news-photos')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_image', to='api.News')),
            ],
        ),
    ]
