# Generated by Django 2.1 on 2018-08-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_newsphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
        migrations.AlterField(
            model_name='newsphoto',
            name='image',
            field=models.ImageField(upload_to='news_photo'),
        ),
    ]
