# Generated by Django 2.1 on 2018-08-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180828_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsphoto',
            name='image',
            field=models.FileField(upload_to='news_photo'),
        ),
    ]
