# Generated by Django 2.1 on 2018-08-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180828_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsphoto',
            name='image',
            field=models.ImageField(upload_to='news_photo'),
        ),
    ]
