# Generated by Django 2.1 on 2018-08-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180828_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва Категорії')),
                ('description', models.CharField(max_length=1000, verbose_name='Опис Категорії')),
                ('category_logo', models.ImageField(null=True, upload_to='category_logo', verbose_name='Катринка Категорії')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
    ]
