# Generated by Django 2.1 on 2018-08-28 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=255, verbose_name='Номер')),
                ('title', models.CharField(max_length=255, verbose_name='Назва пригоди')),
                ('description', models.TextField(verbose_name='Опис пригоди')),
                ('durations_days', models.IntegerField(verbose_name='Тривалість днів')),
                ('durations_night', models.IntegerField(verbose_name='Тривалість ночей')),
                ('price', models.IntegerField(verbose_name='Ціна')),
                ('sale_price', models.IntegerField(blank=True, null=True, verbose_name='Ціна зі скидкою')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення')),
            ],
            options={
                'verbose_name': 'Пригода',
                'verbose_name_plural': 'Пригоди',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(verbose_name='Опис Категорії'),
        ),
        migrations.AddField(
            model_name='journey',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Journeys', to='api.Category', verbose_name='Категорія'),
        ),
    ]
