# Generated by Django 2.1 on 2018-08-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180828_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='JourneyPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journeys_photos')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.Journey')),
            ],
        ),
    ]
